
###
POST http://localhost:10000/fepi/institutes/create HTTP/1.1
Content-Type: application/json

{
  "Nit": "98999",
  "Name": "salle",
  "Location": "calle 67 # 26a 20",
  "Contact": "sofia marin castro",
  "ContactEmail": "sofia@email.com",
  "ContactPhoneNumber": 23456345,
  "State": 1
}

###
GET http://localhost:10000/fepi/institutes HTTP/1.1

###
PUT http://localhost:10000/fepi/institutes/666a21f4c8946305eed64d28 HTTP/1.1
Content-Type: application/json

{

  "Name": "salleee",
  "Location": "calle 67 # 26a 2000",
  "Contact": "daniel",
  "ContactEmail": "daniel@email.com",
  "ContactPhoneNumber": 23456345,
  "State":1
}

# ###
# DELETE http://localhost:3007/institutes/6635123978ce656e3213133c HTTP/1.1

#_________________________________________________________________________________________________________-
###
POST http://localhost:10000/fepi/responsabilities/create HTTP/1.1
Content-Type: application/json

{
  "Description": "organizo papeles y sillas",
  "Location": "sede 2",
  "State":1
}


###
GET http://localhost:10000/fepi/responsabilities HTTP/1.1

# ###
# GET http://localhost:10000/responsabilities/663542d36892a1e111fc6915 HTTP/1.1


###
PUT http://localhost:10000/fepi/responsabilities/666637701b9b2e2b6d37ecd2 HTTP/1.1
Content-Type: application/json

{
  "Description": "Conectar sistemas de sonido",
  "Location": "Fepi-Sede2",
  "Duration": 4,
  "State": 2
}


# ###
# DELETE http://localhost:10000/responsabilities/663542d36892a1e111fc6915 HTTP/1.1

#_________________________________________________________________________________________________________-
###
POST http://localhost:10000/fepi/trainees/create HTTP/1.1
Content-Type: application/json

{
  "FirstName": "sara",
  "LastName": "marin",
  "DocumentType": "Cedula",
  "DocumentNumber": 10388266112,
  "PhoneNumber": 3007546745,
  "Email":"maria@gmail.com",
  "State":2,
  "InstituteID": "663514ef8bb6bedc751d1cf5"
}



###
GET http://localhost:10000/fepi/trainees HTTP/1.1


###
GET http://localhost:10000/fepi/trainees HTTP/1.1


###
PUT http://localhost:10000/fepi/trainees/666916ed81e9251a90ff4fc6 HTTP/1.1
Content-Type: application/json

{
  "FirstName": "jose ",
  "LastName": "herrera",
  "DocumentType": "Cedula",
  "DocumentNumber": 1018935088,
  "State":2,
  "Email":"mariagmail.com",
  "PhoneNumber": 308475888,
  "InstituteID": "6639a1376142dce52eb93c34"

}

# ###
# DELETE http://localhost:3007/trainees/66364ff3e845a4dd4c7275df HTTP/1.1

# _________________________________________________________________________________________________________

###
POST http://localhost:10000/fepi/responsabilitiestrainees/create HTTP/1.1
Content-Type: application/json

{
  "StartDate": "12:01",
  "FinishDate": "1:00",
  "Observations": "planchar",
  "State":2,
  "Duration": "05:30",
  "TraineeID":"6662b80b7661f1f31a61721d",
  "ResponsabilitieID":"666291e57661f1f31a616c4b"
}



###
GET http://localhost:10000/fepi/responsabilitiestrainees HTTP/1.1


###
GET http://localhost:10000/fepi/responsabilitiestrainees HTTP/1.1


###
PUT http://localhost:10000/fepi/responsabilitiestrainees/666a29bf32c434531d636786 HTTP/1.1
Content-Type: application/json

{
  "StartDate": "2:00",
  "FinishDate": "3:02",
  "Observations": "no se que poner aqui ",
  "State":1,
  "Duration": 3,
  "TraineeID": "6636544b806edadb01c8b112",
  "ResponsabilitieID": "663543056892a1e111fc6919"
}



###
# DELETE http://localhost:10000/fepi/responsabilitiestrainees/66720071c1d9497d87c604f9  HTTP/1.1